### ISSUE TITLE
can track back to actual caller line number? 

### ISSUE THREAD

**Issue by naivefun** [caiogondim/logdown.js#41]
Seems it  is printing where logdown.js is right now.

**Comment by caiogondim** [comment]
At first I thought it was technically impossible, but it seems to not be the case http://stackoverflow.com/questions/13815640/a-proper-wrapper-for-console-log-with-correct-line-number

Will work on it

**Comment by ataft** [comment]
The [demo ](https://caiogondim.github.io/logdown.js/)seems to do this. Is this coming soon?

**Comment by caiogondim** [comment]
I checked the demo and it seems to be wrong as well.
Which browser did you checked?

**Comment by ataft** [comment]
Just checked again and you're right, it is wrong. It was showing me index.html, but given that I can't reproduce it I'll just chalk it up to user error.

I'm trying to decide between this api and [loglevel](https://github.com/pimterry/loglevel). Loglevel shows the actual caller line number and also lets you set the level, but I like your api better with the other features. Caller line level is a must tho.

Thanks!

**Comment by caiogondim** [comment]
If loglevel can do, we can do as well :)
Will investigate on how they did it.

**Comment by aga5tya** [comment]
I'm in need of this since most logs are in try-catch for me. @caiogondim Any pointers or info on what was tried,, i will try and make it work similar to loglevel or other libs

**Comment by caiogondim** [comment]
Please do a proof of concept and report your findings here.
If someone did it already, we sure can as well :)

**Comment by aga5tya** [comment]
@caiogondim., I couldn't achieve since the lib gotta parse/format the messages before handing the value/arguments to console object. I'm not sure if the said is possible, since at present loglevel works since it just adds some functionality like enabling and disabling loggers and returns the bound console functions themselves. Hence when invoked, it directly does on console object and properly shows the line number.

I saw another loglevel plugin trying to prefix logs, but that gives the same issue. So unless console supports a function hook or something, im not sure if it can be achieved in any other way. [Link](https://github.com/NatLibFi/loglevel-message-prefix/blob/master/lib/main.js#L157)

And trace or error stack, has the complete stack except logdown line being at the top, so shouldn't be an issue imo. Could add a note in readme so it's clear to others.

**Comment by aga5tya** [comment]
The other thing i can't get to work is the sourcemaps in error stack, anyone has luck with it ? Source maps are enabled with webpack.

**Comment by caiogondim** [comment]
Closing this issue since we don't have a proof of concept.
If we have it, I would be more than happy to implement it.
