### ISSUE TITLE
RFC: 2.0 API

### ISSUE THREAD

**Issue by caiogondim** [caiogondim/logdown.js#72]
Using the same idea as [debug for their V3 release](https://github.com/visionmedia/debug/issues/370), let's discuss ideas for our V2 release.

My current ideas are:

- **Move test suite to Jest**
I don't see value on using Karma and just test if the methods were called with the right values.
Moving to Jest should make everything faster and more straight forward.

- **Use static typing (Flow type or Typescript)**
Should make the lib more stable.

- **Modularize code**
Babel in case of Flow type, Typescript all way down otherwise.

- **Test coverage report**
For free in Jest

- **Full compatibility with [debug](https://github.com/visionmedia/debug/)**
The idea is to make logdown a drop in replacement for debug.
We should run their test suite against our code.
I see this as a high gain, high effort task.

- **Move repo to an organization**
This project is not only mine anymore, and I don't think it's fair to keep it in my name since we have other contributors.
The downside would be SEO.

- **Website**
[logdown.js.org](logdown.js.org) ?

Thoughts?

**Comment by heldr** [comment]
How SEO could affected since github 301 redirect previous routes?

**Comment by caiogondim** [comment]
@heldr Good point. So, no fear regarding this topic =)

**Comment by bennyn** [comment]
This topic is very exciting and would like to give my comment. 🐇 

## Move test suite to Jest
> I don't see value on using Karma and just test if the methods were called with the right values.
Moving to Jest should make everything faster and more straight forward.

I don't know much about Jest but I am very experienced with Karma. Does Jest offer to test Logdown in different browser environments? Because Logdown's output is heavily depending on the browser's console implementation. I see it as a big plus that Karma is able to run a test suite based on the browser. At the time of writing Logdown cannot be used with colorful output in Microsoft Edge (v14). This is something which can be captured with Karma. But can it also be captured with Jest?

## Use static typing (Flow type or Typescript)
> Should make the lib more stable.

I love static typing! This is something which I really miss using JavaScript. That's why I am working with TypeScript in some of my projects, like [bazinga64](https://github.com/wireapp/bazinga64). TypeScript is straightforward and fun if you are not depending on a lot of third party libraries, so it might be applicable for us.

A few days ago I tested flow type and what I like is the concept of gradually adding type assertions. What I didn't like is that you end up writing meta JavaScript code. Because the following is JavaScript code mixed with non-standardized type annotations:

```javascript
// @flow
function bar(x): string {
  return x.length;
}
```

Taking this into account I would prefer TypeScript over flow type. However, selecting TypeScript might decrease the amount of possible contributions since there are less TypeScript developers than there are JavaScript developers. As an open source project (with a large audience) we should therefore pay close attention to the choice of programming language.

For the time being I think it's best to continue with vanilla JavaScript. In order to ensure type safety we can add JSDoc comments in the code because modern IDEs (like WebStorm) are able to [validate JavaScript code with JSDoc types annotations](https://blog.jetbrains.com/webide/2012/10/validating-javascript-code-with-jsdoc-types-annotations/). Another benefit is that there are tools (like [tsd-jsdoc](https://github.com/englercj/tsd-jsdoc)) which are able to generate TypeScript definitions from JSDoc comments, so Logdown can be easily used by TypeScript developers.

## Modularize code
> Babel in case of Flow type, Typescript all way down otherwise.

How is this point to be understood? Logdown is already served as a npm module.

## Test coverage report
> For free in Jest

If we stick to Karma, we can generate code coverage using Istanbul with [karma-coverage](https://github.com/karma-runner/karma-coverage).

## Full compatibility with debug
> The idea is to make logdown a drop in replacement for debug.
We should run their test suite against our code.
I see this as a high gain, high effort task.

More than 800 stargazers confirm that Logdown is already on the right track. If you ask me we should focus on the issues in our backlog first, before we mimic the API of another tool. Of course you could make [debug](https://github.com/visionmedia/debug) users switch to Logdown by offering an API counterpart. However, we are not a company that competes with other companies around customers. So we are free to offer what we think is useful.

## Move repo to an organization
> This project is not only mine anymore, and I don't think it's fair to keep it in my name since we have other contributors.
The downside would be SEO.

I agree that, from a certain size, moving to an organization is appropriate as GitHub gives you more flexibility in user permissions with organizations. My only concern is that this organization would not have more than just two repositories (Logdown.js & Logdown.js website). Perhaps it's worth it to create a JavaScript user group, which is dedicated to write common tools and libraries for a large user circle. This JavaScript user group could than become a GitHub organization which maintains Logdown.js as one of their projects.

## Website
> logdown.js.org ?

I just saw that you can get a [js.org](https://js.org/) domain for free, so that's a really good idea. Even webpack uses ".js.org". However, I  am always worried when the main domain belongs to someone else. You never know where this one stops.

**Comment by caiogondim** [comment]
# Move test suite to Jest
What we are actually testing with Karma right now is if a given method was called with the expected arguments. We cannot test if the actual colors were printed.
What I like about Jest is that is simple.

# Use static typing (Flow type or Typescript)
Not on the top of things we should do, IMHO, since the library is relatively small.
But a nice to have.

# Modularize code
What I mean by this is to rewrite the code in a Node-y way.
Breaking up in small files, and using `require`.

# Test coverage report
I see lots of value on this.

# Full compatibility with debug
That would be nice to be able to just change `debug` to `logdown`.
But indeed not an easy task.

# Move repo to an organization
If we can make the project going here, no problem.

# Website
Not on top of my list as well.
README should be enough for now.
If the library get's complicated (which I hope it doesn't) we can make something like [Redux docs](http://redux.js.org/)

**Comment by caiogondim** [comment]
v3 is published.
- Modular code
- Compatible with `debug` and `util.debuglog`
- Jest for testing
