### ISSUE TITLE
Switching to TypeScript

### ISSUE THREAD

**Issue by bennyn** [caiogondim/logdown.js#94]
One of the reasons why I chose logdown was that it has type definitions which makes it a great choice when using TypeScript. With logdown v3 the type definitions got removed and thus this project is not very user-friendly for TypeScript developers.

Because I ♥ TypeScript I suggest to upgrade the logdown code base to TypeScript. It's not much code that needs to get translated and I can help with it. 😃 

TypeScript was already an option when planning the logdown rewrite (https://github.com/caiogondim/logdown.js/issues/72), so it's a great time to bring up that topic again. WDYT?

**Comment by caiogondim** [comment]
My main concern regarding that is that we "lose control" over the final bundle.
Bundle size for a frontend library is important, and I don't see much value on switching to TS on such a small lib.

Even though I think we should provide the type definitions since TS is very popular.

@bennyn Can you make a PR for type definitions? :)

**Comment by caiogondim** [comment]
Or maybe we can use JSDoc for that https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript

**Comment by caiogondim** [comment]
Just made a small exp with JSDoc + TypeScript: https://github.com/caiogondim/parse-price.js/blob/master/src/index.js

This way we gain type annotations and don't lose control from final output.

**Comment by bennyn** [comment]
**Uh, great!** I didn't knew that TypeScripts can read types from JSDoc out of the box. 

At [Wire](https://wire.com/) we did some experiments with [tsd-jsdoc](https://github.com/englercj/tsd-jsdoc). But we had to use a special version to make it work: https://github.com/wireapp/proteus.js/blob/v5.2.0/package.json#L14

**Comment by caiogondim** [comment]
I did some more reading on this regard, because I want to implement here at work but without transpilation (so we can deliver a as-is JS file for modern browsers).

TypeScript with JSDoc supports only a subset of TypeScript.
With Flow we can do the same approach and get 100% features.
I would go with Flow.

But honestly, for this lib, I wouldn't implement neither of them.
Tests should be enough and we don't have big data pipelines (which static type would help).

**Comment by caiogondim** [comment]
Should we close this issue and create one providing the typings for logdown again? 😉

**Comment by SleepWalker** [comment]
> without transpilation 

If you'll use `flow`. You can use `babel` plugin, that will only strip type annotations from source code leaving the rest as it was before.

I agree, that such small lib can live without static typing, but I love, when they are present in code :)

Regarding `chose logdown was that it has type definitions`. This things can be provided without covering the entire code base with type annotations if I'm not mistaken (at least for flow-type it is true)

**Comment by caiogondim** [comment]
Since TypeScript is getting more and more popular, guess we should provide a `.d.ts` file.

**Comment by voznik** [comment]
hello. is there any update on when you can provide a `*.d.ts` file for Typescript?

**Comment by caiogondim** [comment]
Type definition here https://github.com/caiogondim/logdown.js/blob/master/index.d.ts
